### ISSUE TITLE
Unreadable text on the submissions page

### ISSUE THREAD

**Issue by m3hu1** [ashish0kumar/LeetCode-Catppuccin#6]
- When there is no distribution chart, the text is unreadable as shown in the screenshot.
> <img width="1239" alt="SCR-20241108-kteq" src="https://github.com/user-attachments/assets/9386af08-815d-4487-bcef-c768d966d74c">

- For reference
> <img width="1225" alt="SCR-20241108-ktil" src="https://github.com/user-attachments/assets/f2200275-655a-44bf-b5d0-cb6292e7120c">

- Also, as seen in the first screenshot, the submitted code is not very readable due to the current syntax highlighting colors.
> <img width="788" alt="image" src="https://github.com/user-attachments/assets/38a18a86-a689-4c71-b83e-489bdc9bc82b">

**Comment by ashish0kumar** [comment]
Is there a way to access the submission page that doesn't have a distribution chart? I need to know the class of that unreadable text.

**Comment by m3hu1** [comment]
Just go to any latest contest problem on leetcode and submit a soln using a
less used language like rust or some other language and u should be able to
get that page.
